### PR TITLE
Add query with TCP feature

### LINKED ISSUE #24: Support DNS over TCP
This (arguably awesome) library currently only supports DNS lookups over UDP. This is acceptable for most use-cases of DNS. It is, however, very useful to have the ability to respond over TCP. This is useful in cases of, for example: zone transfers and DNSSEC. Therefore, implementing a TCP frontend as well, is a necessity.

### LINKED ISSUE #31: Providing a bad DNS server results in hanging indefinitely
Using `resolve/3` like so:

`DNS.resolve("google.com", :a, {"not.a.dns.server.com", 53})`

Results in the call hanging indefinitely (or at least appears to hang indefinitely). This can be corrected by using `recv!/2` rather than `recv!/1` with a timeout option here: 

https://github.com/tungd/elixir-dns/blob/master/lib/dns.ex#L48

I forked and made this change for my own purposes for now (https://github.com/silverp1/elixir-dns/commit/08c535afe84afc725edd9b0b99bdfaa6f41ee917) but figured I'd raise the issue to see what folks think about doing something like this in master.

My use case here is a monitoring application where users supply the record to check as well as the DNS server to query.

### PR DESCRIPTION
**Pull request by Fitblip**
Hi there!

This PR does 3 main things:
- Adds in a `:tcp` option for `DNS.resolve` and `DNS.query`, which fixes #24. It looks like this:
    ```elixir
    iex(1)> DNS.resolve("google.com", :a, {"127.0.0.1", 53}, :tcp)
    {:ok, [{172, 217, 3, 78}]}
    iex(2)> DNS.query("google.com", :a, {"127.0.0.1", 53}, :tcp)
    %DNS.Record{
      anlist: [
        %DNS.Resource{
          bm: [],
    ...SNIP...
    ```
- It reworks some of the connection logic, removing the `import Socket.Datagram` and calling UDP functions directly to better differentiate the `send!`/`recv!` functions now that there is TCP connections too. I also added 5 second timeouts to both TCP and UDP calls, which fixes #31 (and supersedes #35, which I'll be closing)
- It adds a `DNS.ResourceOpt` module to the top of `resource.ex`, without it there the library is unable to be used due to a breaking change in #32. I submitted #34, but will also be closing it in lieu of this PR.

Minor things
- Cleans up some function specs, adds some docs
- Adds a test for TCP DNS queries that mirrors the UDP version.
- Bumped version to `2.2.0` since this introduces a new feature 🚀
- Updates travis config to run against more modern versions of elixir/otp

### CODE REVIEW

**Comment by Fitblip** [comment]
Hey @tungd, I think this is ready to go now if you don't mind reviewing!

**Comment by tungd** [comment]
Merged! Thanks a lot for contributing. A new release will be published to Hex soon. 🎉

**Comment by Fitblip** [comment]
Wonderful, thanks @tungd :). Thanks for the speedy merge and for such a great library!

**Comment by tungd** [comment]
@Fitblip version v2.2.0 has been released and is now available on Hex.

**Pull request merged**
